### ISSUE TITLE
share --setup doesn't create the ~/.config/sharecmd directory

### ISSUE THREAD

**Issue by iliyas-shirol** [mschneider82/sharecmd#1]
I used the binary `sharecmd_0.0.35_Linux_x86_64.tar.gz` on my Arch system. While setting up the auth using `share --setup` it exited successfully with the following message,

Saving config to `/home/iliyas/.config/sharecmd/config.json`

But the config isn't getting written as the parent directory `sharecmd/` is missing. It'd be better to handle this in the code.

**Comment by mschneider82** [comment]
Hi @iliyas-shirol 
thanks for reporting, it should be fixed in 0.0.40!
