### ISSUE TITLE
Unable to retain .xlsx file format after upload

### ISSUE THREAD

**Issue by iliyas-shirol** [mschneider82/sharecmd#4]
If a .xlsx file is uploaded using the utility, it extracts the file components instead of opening the file in the sheets. PFA

![image](https://user-images.githubusercontent.com/3808336/50213082-9ae82080-03a2-11e9-86e8-e84ba756dc44.png)

**Comment by mschneider82** [comment]
hi @iliyas-shirol 

Should be fixed in the latest version 0.0.64
