### ISSUE TITLE
macOS 10.14.6 No URL

### ISSUE THREAD

**Issue by scgf** [mschneider82/sharecmd#6]
I installed sharecmd through HomeBrew and configured it to point to my NextCloud server. When I share a file, eg. 'share Desktop/Misc/Co-opBank.png' the file is correctly copied to my NextCloud sharecmd folder and everything seems to work except that the URL field is empty and nothing is copied to the clipboard. I have tried with and without the URL shortener to no avail. Am I doing something wrong?

<img width="397" alt="Screenshot 2019-09-05 at 12 37 55" src="https://user-images.githubusercontent.com/42443376/64338580-12fe8100-cfda-11e9-84e5-8c032848afb0.png">

**Comment by mschneider82** [comment]
It seems that the urlshortener Biturl.top is down, you have to turn url shortener off.

What version on Nextcloud are you trying? It seems that the share doesnt reply a url (the user has share file rights?)

**Comment by mschneider82** [comment]
Can you provide me a temp user and the nextcloud url so i can test and debug it? mail: ms@wck.biz

**Comment by scgf** [comment]
Hey that was quick! Thank you. I have already turned off url shortener.

I am using NextCloud 16.0.4

I have created a user 'tempuser' with pw '4vvTn*Hf'

The NextCloud url is https://scgf.synology.me:60443/nextcloud

If I need to do anything else to this user please let me know.

**Comment by mschneider82** [comment]
I have created a new version 0.0.93 for better error logging with nextcloud, you can see that you get the following message from your nextcloud instance:

```
2019/09/05 14:05:18 Can't get link for file: Status: failure, Message: Invalid query, please check the syntax. API specifications are here: http://www.freedesktop.org/wiki/Specifications/open-collaboration-services.
```
According please check the issues from  github.com/nextcloud/server/ there are many others getting this

**Comment by scgf** [comment]
Thank you. I will investigate.
