### ISSUE TITLE
Support for link share passwords on Nextcloud

### ISSUE THREAD

**Issue by moritzheiber** [mschneider82/sharecmd#7]
Some Nextcloud instances are enforcing settings a password for link sharing now, which means whenever you try to use `share` with such an instance you'll get the following error:

```
$ share some-file
Uploading [...]
2020/05/03 13:38:20 Can't get link for file: Status: failure, Message: Passwords are enforced for link shares
```
I would be cool to have `share` generate a reasonably secure, random password and post it to the command line along with the URL, so this use-case is supported.

**Comment by mschneider82** [comment]
Hi, 

I found it in api docs https://docs.nextcloud.com/server/stable/developer_manual/client_apis/OCS/ocs-share-api.html?highlight=sharetype#create-a-new-share

Unfortually i have to first setup a nextcloud instance or use docker. This needs some time. Can you provide me an temp account to test, so i can skip the setup?

**Comment by moritzheiber** [comment]
Sure, absolutely. How can I get the account information to you securely? Do you have GPG?

**Comment by mschneider82** [comment]
By mail: ms AT wck.biz

**Comment by moritzheiber** [comment]
Just to make sure, there is no GPG identity associated with this address?

**Comment by mschneider82** [comment]
Nope. But you can delete the account after tests are completed

**Comment by moritzheiber** [comment]
Email sent.

**Comment by mschneider82** [comment]
Can you please test latest build 105, you have todo --setup again

**Comment by moritzheiber** [comment]
Works as intended! One last question: Is there a way of finding out the password requirements (mine are "at least 32 characters") and offering them up as a default?

**Comment by mschneider82** [comment]
Cannot find any info about a policy query in the API docs. So my default is also 32. I doubt that anyone has a larger default
